### ISSUE TITLE
META: Feature Model View and SVG Export

### ISSUE THREAD

**Issue by h3ssto** [OBDDimal/cofmed#16]
TODO:
* [ ] Mark items as implemented in viewer ( :pineapple: ) and fm2svg ( :eggplant: )
    * Viewer: Implemented and available through UI
    * fm2svg: Implemented and supported by API 
* [ ] Discuss list with @LukasOsti @tomatenhans 
* [ ] Breakout issues for bugged ( :lady_beetle: ), missing features ( :mag: )

----

We plan to support the following list of styling options for coFMed:

# Styling Options

### Direction
XOR

* horizontal :pineapple: :eggplant: 
* vertical
    * with overlaps
    * without overlaps :pineapple: :eggplant: 

### Meta Collapsing
XOR - top to bottom, left to right

* Show n features
    * [ ] Breadt-First, Depth-First

### Collapsing of Levels
XOR 

* Max levels (top-aligned), open the first n levels :pineapple: 
* Set of levels, e.g., {1, 4, 5} -> Levels 1, 4, 5 uncollapsed, rest collapsed
    * [ ] Requires vertical collapsing in between [#14](https://github.com/OBDDimal/cofmed/issues/14)

### Collapsing of Children
Basic rule: left-aligned, collapse right to left

* Max children, e.g., 3 -> Maximum number of children per feature is 3 :pineapple:
* Max total children, e.g., 7 -> Show at most 7 features in a level

### Draw Distance
* Level Distance :pineapple: :eggplant: 
* Sibling Distance :pineapple: :eggplant: 

#### Color Schemes
Draw, Fill, Text Color, Text Style

* variability.dev :pineapple: :eggplant: 
* FeatureIDE (todo)
* High Contrast ...
* By css

#### Options
* Background :eggplant: 
* Feature
    * Default :eggplant: 
    * Abstract :eggplant: 
    * Marked
* Anomaly Features (requires solver)
    * Core
    * Dead
    * False-Optional
* Edges
    * Default
    * Marked
* Anomaly Features (requires solver)
    * False-Optional
    * ...
* Others
    * Collapsed Triangle & Collapsed Placeholder
        * Border = Feature
        * Text   = Feature Text
        * Fill   = Feature

## Text
Color + Style

* Feature
    * Default :eggplant: 
    * Abstract :eggplant: 
    * Marked
* Anomaly Features (requires solver)
    * Core
    * Dead
    * False-Optional

## Misc
* Short Names :pineapple: :eggplant:
